# This docker file embeds a pre-built binary (usually from the github actions runner)

FROM gcr.io/distroless/base

ARG TARGETARCH

WORKDIR /app

# Copy the architecture-specific server binary produced by the workflow
COPY ./server/server-${TARGETARCH} /app/server
EXPOSE 3001

CMD ["/app/server"]