# This docker file embeds a pre-built binary (usually from the github actions runner)

FROM gcr.io/distroless/base

ARG TARGETARCH

WORKDIR /app

COPY ./server /app/server

EXPOSE 3001

CMD ["/app/server"]