FROM node:24-bookworm-slim AS build

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/api/package.json apps/api/package.json

RUN pnpm install --frozen-lockfile --filter api...

COPY apps/api apps/api

RUN pnpm --filter api build \
	&& pnpm --filter api deploy --prod /prod/api

FROM node:24-bookworm-slim

WORKDIR /app

ENV NODE_ENV="production"
ENV PATH="/app/node_modules/.bin:$PATH"

COPY --from=build /prod/api ./

EXPOSE 3001

CMD ["node", "dist/server.js"]
