name: Build
 
on:
  push:
    branches: ["main"]
  workflow_run:
    workflows: [Merge Bot]
    types:
      - completed
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
 
jobs:
  build:
    name: API Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
 
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/api
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha,format=long

      - name: Cache bun and project bun dir
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun
            ~/.cache/bun
            apps/api/.bun
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install api dependencies
        run: bun install --filter "api"

      - name: Build api binaries
        run: |
          mkdir -p server
          bun build --compile --minify-whitespace --minify-syntax --target bun-linux-arm64 --outfile server/server-arm64 apps/api/src/index.ts
          chmod +x server/server-arm64
          bun build --compile --minify-whitespace --minify-syntax --target bun-linux-x64 --outfile server/server-amd64 apps/api/src/index.ts
          chmod +x server/server-amd64

      - name: Build and push container image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: docker/Dockerfile-api
          cache-from: type=gha
          cache-to: type=gha,mode=max